class AirlinesData {
  static const List<Map<String, String>> airlines = [
    {'name': 'Aegean Airlines', 'code': 'A3'},
    {'name': 'Aer Lingus', 'code': 'EI'},
    {'name': 'Aeroflot', 'code': 'SU'},
    {'name': 'Aerolineas Argentinas', 'code': 'AR'},
    {'name': 'Aeromexico', 'code': 'AM'},
    {'name': 'Air Arabia', 'code': 'G9'},
    {'name': 'Air Astana', 'code': 'KC'},
    {'name': 'Air Baltic', 'code': 'BT'},
    {'name': 'Air Canada', 'code': 'AC'},
    {'name': 'Air China', 'code': 'CA'},
    {'name': 'Air Europa', 'code': 'UX'},
    {'name': 'Air France', 'code': 'AF'},
    {'name': 'Air India', 'code': 'AI'},
    {'name': 'Air Macau', 'code': 'NX'},
    {'name': 'Air Malta', 'code': 'KM'},
    {'name': 'Air Mauritius', 'code': 'MK'},
    {'name': 'Air Namibia', 'code': 'SW'},
    {'name': 'Air New Zealand', 'code': 'NZ'},
    {'name': 'Air Niugini', 'code': 'PX'},
    {'name': 'Air Peace', 'code': 'P4'},
    {'name': 'Air Serbia', 'code': 'JU'},
    {'name': 'Air Seychelles', 'code': 'HM'},
    {'name': 'Air Tahiti Nui', 'code': 'TN'},
    {'name': 'Air Transat', 'code': 'TS'},
    {'name': 'Air Vanuatu', 'code': 'NF'},
    {'name': 'AirAsia', 'code': 'AK'},
    {'name': 'AirAsia X', 'code': 'D7'},
    {'name': 'Aircalin', 'code': 'SB'},
    {'name': 'Alaska Airlines', 'code': 'AS'},
    {'name': 'Alitalia', 'code': 'AZ'},
    {'name': 'All Nippon Airways', 'code': 'NH'},
    {'name': 'Allegiant Air', 'code': 'G4'},
    {'name': 'American Airlines', 'code': 'AA'},
    {'name': 'Arik Air', 'code': 'W3'},
    {'name': 'Asiana Airlines', 'code': 'OZ'},
    {'name': 'Austrian Airlines', 'code': 'OS'},
    {'name': 'Avianca', 'code': 'AV'},
    {'name': 'Azerbaijan Airlines', 'code': 'J2'},
    {'name': 'Azul Brazilian Airlines', 'code': 'AD'},
    {'name': 'Bamboo Airways', 'code': 'QH'},
    {'name': 'Bangkok Airways', 'code': 'PG'},
    {'name': 'Biman Bangladesh Airlines', 'code': 'BG'},
    {'name': 'Binter Canarias', 'code': 'NT'},
    {'name': 'British Airways', 'code': 'BA'},
    {'name': 'Brussels Airlines', 'code': 'SN'},
    {'name': 'Cathay Dragon', 'code': 'KA'},
    {'name': 'Cathay Pacific', 'code': 'CX'},
    {'name': 'Cebu Pacific', 'code': '5J'},
    {'name': 'China Airlines', 'code': 'CI'},
    {'name': 'China Eastern Airlines', 'code': 'MU'},
    {'name': 'China Southern Airlines', 'code': 'CZ'},
    {'name': 'Condor', 'code': 'DE'},
    {'name': 'Copa Airlines', 'code': 'CM'},
    {'name': 'Croatia Airlines', 'code': 'OU'},
    {'name': 'Czech Airlines', 'code': 'OK'},
    {'name': 'Delta Air Lines', 'code': 'DL'},
    {'name': 'easyJet', 'code': 'U2'},
    {'name': 'EgyptAir', 'code': 'MS'},
    {'name': 'El Al Israel Airlines', 'code': 'LY'},
    {'name': 'Emirates', 'code': 'EK'},
    {'name': 'Ethiopian Airlines', 'code': 'ET'},
    {'name': 'Etihad Airways', 'code': 'EY'},
    {'name': 'EVA Air', 'code': 'BR'},
    {'name': 'Fiji Airways', 'code': 'FJ'},
    {'name': 'Finnair', 'code': 'AY'},
    {'name': 'flydubai', 'code': 'FZ'},
    {'name': 'FlyEgypt', 'code': 'FT'},
    {'name': 'Frontier Airlines', 'code': 'F9'},
    {'name': 'Garuda Indonesia', 'code': 'GA'},
    {'name': 'Gol Transportes Aéreos', 'code': 'G3'},
    {'name': 'Gulf Air', 'code': 'GF'},
    {'name': 'Hainan Airlines', 'code': 'HU'},
    {'name': 'Hawaiian Airlines', 'code': 'HA'},
    {'name': 'Hong Kong Airlines', 'code': 'HX'},
    {'name': 'Iberia', 'code': 'IB'},
    {'name': 'Iberia Express', 'code': 'I2'},
    {'name': 'Icelandair', 'code': 'FI'},
    {'name': 'IndiGo', 'code': '6E'},
    {'name': 'Iran Air', 'code': 'IR'},
    {'name': 'Japan Airlines', 'code': 'JL'},
    {'name': 'Jeju Air', 'code': '7C'},
    {'name': 'Jet2.com', 'code': 'LS'},
    {'name': 'JetBlue Airways', 'code': 'B6'},
    {'name': 'Jetstar Airways', 'code': 'JQ'},
    {'name': 'Jetstar Asia Airways', 'code': '3K'},
    {'name': 'Jetstar Japan', 'code': 'GK'},
    {'name': 'Kenya Airways', 'code': 'KQ'},
    {'name': 'KLM', 'code': 'KL'},
    {'name': 'Korean Air', 'code': 'KE'},
    {'name': 'Kuwait Airways', 'code': 'KU'},
    {'name': 'LATAM Airlines', 'code': 'LA'},
    {'name': 'Lion Air', 'code': 'JT'},
    {'name': 'LOT Polish Airlines', 'code': 'LO'},
    {'name': 'Lufthansa', 'code': 'LH'},
    {'name': 'Luxair', 'code': 'LG'},
    {'name': 'Mahan Air', 'code': 'W5'},
    {'name': 'Malaysia Airlines', 'code': 'MH'},
    {'name': 'Middle East Airlines', 'code': 'ME'},
    {'name': 'Nok Air', 'code': 'DD'},
    {'name': 'Nordwind Airlines', 'code': 'N4'},
    {'name': 'Norwegian Air Shuttle', 'code': 'DY'},
    {'name': 'Oman Air', 'code': 'WY'},
    {'name': 'Pakistan International Airlines', 'code': 'PK'},
    {'name': 'Pegasus Airlines', 'code': 'PC'},
    {'name': 'Philippine Airlines', 'code': 'PR'},
    {'name': 'Porter Airlines', 'code': 'PD'},
    {'name': 'Qantas Airways', 'code': 'QF'},
    {'name': 'Qatar Airways', 'code': 'QR'},
    {'name': 'RwandAir', 'code': 'WB'},
    {'name': 'Ryanair', 'code': 'FR'},
    {'name': 'S7 Airlines', 'code': 'S7'},
    {'name': 'SAS Scandinavian Airlines', 'code': 'SK'},
    {'name': 'Saudia', 'code': 'SV'},
    {'name': 'Scoot', 'code': 'TR'},
    {'name': 'Shanghai Airlines', 'code': 'FM'},
    {'name': 'Shenzhen Airlines', 'code': 'ZH'},
    {'name': 'Siberia Airlines', 'code': 'S7'},
    {'name': 'Sichuan Airlines', 'code': '3U'},
    {'name': 'SilkAir', 'code': 'MI'},
    {'name': 'Singapore Airlines', 'code': 'SQ'},
    {'name': 'Sky Airline', 'code': 'H2'},
    {'name': 'SkyWest Airlines', 'code': 'OO'},
    {'name': 'South African Airways', 'code': 'SA'},
    {'name': 'Southwest Airlines', 'code': 'WN'},
    {'name': 'SpiceJet', 'code': 'SG'},
    {'name': 'Spirit Airlines', 'code': 'NK'},
    {'name': 'Spring Airlines', 'code': '9C'},
    {'name': 'SriLankan Airlines', 'code': 'UL'},
    {'name': 'Sun Country Airlines', 'code': 'SY'},
    {'name': 'Sunwing Airlines', 'code': 'WG'},
    {'name': 'Swiss International Air Lines', 'code': 'LX'},
    {'name': 'TAAG Angola Airlines', 'code': 'DT'},
    {'name': 'TAP Air Portugal', 'code': 'TP'},
    {'name': 'TAROM', 'code': 'RO'},
    {'name': 'Thai AirAsia', 'code': 'FD'},
    {'name': 'Thai Airways', 'code': 'TG'},
    {'name': 'Thai Lion Air', 'code': 'SL'},
    {'name': 'TUI Airways', 'code': 'BY'},
    {'name': 'Tunisair', 'code': 'TU'},
    {'name': 'Turkish Airlines', 'code': 'TK'},
    {'name': 'Ukraine International Airlines', 'code': 'PS'},
    {'name': 'United Airlines', 'code': 'UA'},
    {'name': 'Ural Airlines', 'code': 'U6'},
    {'name': 'UTair Aviation', 'code': 'UT'},
    {'name': 'Uzbekistan Airways', 'code': 'HY'},
    {'name': 'VietJet Air', 'code': 'VJ'},
    {'name': 'Vietnam Airlines', 'code': 'VN'},
    {'name': 'Virgin Atlantic', 'code': 'VS'},
    {'name': 'Virgin Australia', 'code': 'VA'},
    {'name': 'Vistara', 'code': 'UK'},
    {'name': 'Volaris', 'code': 'Y4'},
    {'name': 'Vueling', 'code': 'VY'},
    {'name': 'WestJet', 'code': 'WS'},
    {'name': 'Wizz Air', 'code': 'W6'},
    {'name': 'XiamenAir', 'code': 'MF'},
  ];
}
